---
output:
  html_document:
    css: styles.css
---
<h2 class="Publications">Job Market Papers</h2>

<h2 class="title2">Campaign rallies and infant health: the case of Donald Trump</h2>

<h2 class="abstract-title">Abstract</h2>
Politics affects health. While the influence of enacted policies on health is well-established, there is limited empirical investigation into the health impacts of politics prior to policy change. This study investigates the consequences of Donald Trump's 2015-2016 presidential campaign rallies on infant health in the United States. Linking geographically located data on Trump rallies to monthly, county-level U.S. birth records, the research employs the timing of these rallies as a quasi-experimental shock within counties that held a Trump rally to analyze their effects on adverse birth outcomes. Prenatal exposure to Trump rallies increased the percentage of very low birthweight among infants born to foreign-born Hispanic women, and low birthweight of infants born to foreign-born Asian and Pacific Islander (API) women in counties that hosted a rally as early as during the Republican primary period. This effect was not observed among U.S.-born women or foreign-born White, or Black women. The harmful effects are concentrated in the counties Trump visited and do not extend to neighboring counties. The ethnicity and race-specific health effects suggest that Trump's presidential rallies constituted a significant stressor for Hispanic and API foreign-born groups residing in the U.S. Further, this study underscores one significant finding: presidential candidates can influence population health even before elected. 

<h2 class="title2">U.S. states’ prioritization of carceral spending and Black & White death </h2>

<h2 class="abstract-title">Abstract</h2>
Overarching policy and political contexts shape health inequities. However, how the clustering of policies into ‘policy regimes’ beyond welfare impacts health, has received limited empirical attention. Since the 1980s the U.S. has expanded a penal-welfare regime involving the increasing use of prisons, courts, and police to address poverty and simultaneous retraction of welfare protections. This paper explores the population-level health consequences of people’s exposure to a penal-welfare regime that prioritizes punitive control over welfare support. It examines the association between a states’ prioritization of carceral spending over health and welfare expenditure and Black and White death in 42 U.S. states between 1980 and 2008. Using fixed-effects models and controlling for confounders, I find that U.S. states’ fiscal prioritization of carceral systems to the exclusion of health and welfare is associated with an increased number of Black and White deaths. The association between a states’ carceral prioritization and Black death is larger than its association with White death. Further, these negative consequences are concentrated in the South for both groups and in the West for White groups. My findings suggest that a penal-welfare regime that prioritizes punitive control over welfare support harms overall population health, and disproportionately the health of Black groups living in the South. 

<h2 class="Publications">Publications</h2>

- [Langer P., Patler C., Hamilton E. (2024) The 2016 US presidential election was disproportionately associated birth outcomes for infants born to Black and Hispanic mothers. Demography](https://read.dukeupress.edu/demography/article/61/4/1211/390020/Adverse-Infant-Health-Outcomes-Increased-After-the)

- [Hamilton, E. R., Masferrer, C., & Langer, P. (2022). US Citizen Children De Facto Deported to Mexico. Population and Development Review](https://onlinelibrary.wiley.com/doi/abs/10.1111/padr.12521)

- [Hamilton E., Langer P., Patler C., (2021). DACA’s association with birth outcomes among Mexican-origin mothers in the United States. Demography. ](https://read.dukeupress.edu/demography/article/58/3/975/172654/DACA-s-Association-With-Birth-Outcomes-Among)

- [Hamilton E., Patler C., Langer P. (2021) The Life-Course Timing of Legalization: Evidence from the DACA Program, Socius.](https://journals.sagepub.com/doi/pdf/10.1177/23780231211058958) 

- [Pérez-Cruz, P. E., Langer, P., Carrasco, C., Bonati, P., Batic, B., Tupper Satt, L., & Gonzalez Otaiza, M. (2019). Spiritual Pain Is Associated with Decreased Quality of Life in Advanced Cancer Patients in Palliative Care: An Exploratory Study. Journal of palliative medicine](https://www.liebertpub.com/doi/full/10.1089/jpm.2018.0340)

<h2 class="Publications">Forthcoming</h2>

- Hamilton E., Masferrer, C., & Langer, P. (Forthcoming) Parent-child separation and plans for family reunification after deportation to Mexico from the United States. Migraciones Internacionales

<h2 class="Publications">Under review</h2>

- Langer P., Campaign rallies and infant health: the case of Donald Trump

- Patler C., Saadi A., Langer P., The health-related experiences of detained immigrants with and without mental illness

- Patler C., Langer P., Has population mental health returned to pre-pandemic levels, among and between groups by race and immigration status?

- Saadi A., Patler C., Langer P., Duration in Immigration Prison as a Mechanism for Health Harms Among Detained Immigrants

<h2 class="Publications">Selected work in progress</h2>

- Langer P., U.S. states’ prioritization of carceral spending and Black & White death

- Langer P., Patler C., The impact of DACA on the payment source for delivery

- Langer P., Baughman E., Transitions to adulthood among disabled native and foreign-born adults

